name = "cp-review-cron-worker"
main = "src/index.ts"
compatibility_date = "2024-02-08"

[triggers]
crons = ["0 */2 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "cp-review"
database_id = "482f5bfb-5991-4980-89c8-df4837ec5c54"
