name: Update AC List Data

on:
  schedule:
    # 週 1 で commit する
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install deps
        run: yarn install
      - name: Update data
        run: yarn update-data
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update AC List Data"
          title: "[Auto] Update AC List Data"
          branch-suffix: "short-commit-hash"
